# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.dropNonIntermediateRootMethods=true
# Mod Metadata
group=ink.quietly
user=username
slug=lampblack
modId=lampblack
modName=lampblack
modDescription=a terribly simple pronoun mod
authors=iridith
contributors=
license=MIT
# Mod Version
modVersion=1.2.0
# Branch Metadata
branchName=1.21.1
compatibleVersions=1.21.1
compatibleLoaders=fabric, quilt, neoforge
