# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=ink.quietly
user=username
slug=lampblack
modId=lampblack
modName=lampblack
modDescription=a terribly simple pronoun mod
authors=iridith
contributors=Sisby folk
license=MIT
# Mod Version
modVersion=1.3.0
# Branch Metadata
branchName=26.1
compatibleVersions=26.1
compatibleLoaders=fabric
